# nixpacks.toml

[phases.setup]
nixPkgs = [
  "php80",
  "php80Extensions.pdo_mysql",
  "php80Extensions.mbstring",
  "php80Extensions.fileinfo"
]

[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader --no-scripts"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host 0.0.0.0 --port $PORT"
